config/routes.rb
Squawkem::Application.routes.draw do

  get "categories/index"

  get "categories/show"

  get "category/index"

  get "category/show"

  devise_for :users

  resources :businesses do
    resources :reviews
  end

  resources :categories
  
  resources :reviews

  resources :searches

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/thanks',  :to => 'pages#thanks'
  match '/tour',  :to => 'pages#tour'

  #match 'search/' => 'search#index'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  before_filter :authenticate_user!

  helper_method :sort_column, :sort_direction

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.order(sort_column + " " + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @businesses }
    end
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @business = Business.find(params[:id])
    @json = @business.to_gmaps4rails
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/new
  # GET /businesses/new.json
  def new
    @business = Business.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/1/edit
  def edit
    @business = Business.find(params[:id])
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(params[:business])

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render json: @business, status: :created, location: @business }
      else
        format.html { render action: "new" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /businesses/1
  # PUT /businesses/1.json
  def update
    @business = Business.find(params[:id])

    respond_to do |format|
      if @business.update_attributes(params[:business])
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business = Business.find(params[:id])
    @business.destroy

    respond_to do |format|
      format.html { redirect_to businesses_url }
      format.json { head :ok }
    end
  end

  private
  
  def sort_column
    Business.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end


end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="clearfix">
    <%= f.label :name, :for => "xlInput" %>
     <div class="input">
      <%= f.text_field :name %>
    </div>
  </div> 
  <div class="clearfix">
    <%= f.label :address, :for => "xlInput" %>
     <div class="input">
      <%= f.text_field :address %>
    </div>
  </div> 
  
  <div class="clearfix">
    <%= f.label :city, :for => "xlInput" %>
     <div class="input">
      <%= f.text_field :city %>
    </div>
  </div> 
  <div class="clearfix">
    <%= f.label :state, :for => "xlInput" %>
     <div class="input">
      <%= f.text_field :state %>
    </div>
  </div>  
  
  <div class="clearfix">
    <%= f.label :phone, :for => "xlInput" %>
     <div class="input">
      <%= f.text_field :phone %>
    </div>
  </div> 
  <div class="clearfix">
    <%= f.label :url, :for => "xlInput" %>
     <div class="input">
      <%= f.text_field :url %>
    </div>
  </div>  

  <div class="clearfix">
    <%= f.label :description, :for => "xlInput" %>
     <div class="input">
      <%= f.text_area :description, :rows => '3', :class => 'xxlarge' %>
    </div>
  </div> 

  <div class="clearfix input">
    <% Category.order(:name).each do |category| %>
      <div class="pull-left">
        <div class="input-prepend">
          <label class="add-on">
            <%= check_box_tag "business[category_ids][]", category.id, @business.categories.include?(category) %>
          </label>
          <input class="large uneditable-input" name="prependedInput2" id="prependedInput2" size="30" type="text" value="<%= category.name %>" >
        </div>
      </div>
    <% end %>
  </div>

  <div class="clearfix">
    <div class="input">
      <%= f.submit "Go!", :class =>"btn small primary" %>
    </div>
  </div>

<% end %>

app/views/businesses/_table_header.html.erb
 <thead> 
  <tr>
    <th>Business</th>
    <th>City</th>
    <th><%= link_to('S', '#', :rel => "popover", :"data-original-title" => "Speed", :"data-content" => 'Did they get the work done quickly?   
      <UL >
        <li> 5 for Really Fast </li>
        <li> 4 for Fast Enough </li>
        <li> 3 for Average </li>
        <li> 2 Somewhat Slow </li>
        <li> 1 for Really Slow </li>
      </UL>' )%> </th>
    <th><%= link_to('Q', '#', :rel => "popover", :"data-original-title" => "Quality", :"data-content" => 'Did they do a good job? 
      <UL >
        <li> 5 for Really Nice </li>
        <li> 4 for Good Enough </li>
        <li> 3 for Average </li>
        <li> 2 Somewhat OK </li>
        <li> 1 for Really Bad </li>
      </UL>' )%> </th>
    <th><%= link_to('U', '#', :rel => "popover", :title => "Usability", :"data-content" => 'Are they easy to contact and schedule? Do they return calls same day? Can they be scheduled for same week appointments? 
      <UL>
        <LI> 5 for Really Easy </LI>
        <LI> 4 for Easy Enough </LI>
        <LI> 3 for Average </LI>
        <LI> 2 for Somewhat Hard to Use </LI>
        <LI> 1 for Very Busy </LI>
      </UL>' )%> </th>
    <th><%= link_to('A', '#', :rel => "popover", :title => "Affordability", :"data-content" => 'Do they give the best prices?
      <UL>
        <LI> 5 for Always The Best Price </LI>
        <LI> 4 for Pretty Good Deal </LI>
        <LI> 3 for Average </LI>
        <LI> 2 for A Bit Expensive </LI>
        <LI> 1 for Really Expensive </LI>
      </UL>' )%> </th>
    <th><%= link_to('W', '#', :rel => "popover", :title => "Warranty", :"data-content" => 'Do they stand behind their work?  How good are they at fixing problems that arise?
      <UL>
        <LI> 5 for Excellent At Getting Problems Fixed </LI>
        <LI> 4 for Good Enough </LI>
        <LI> 3 for Average </LI>
        <LI> 2 for Below Average </LI>
        <LI> 1 for No Warranty </LI>
      </UL>' )%> </th>
    <th><%= link_to('K', '#', :rel => "popover", :title => "Kindness", :"data-content" => 'Are they kind, careful, and clean?
      <UL>
        <LI> 5 for Very Professional </LI>
        <LI> 4 for Careful Enough </LI>
        <LI> 3 for Average </LI>
        <LI> 2 for Somewhat Unkind </LI>
        <LI> 1 for Very Unproffesional </LI>
      </UL>' )%> </th>
    <th>Average</th>
    <%= !params[:search_near].blank? ? "<th>Distance</th>".html_safe : '&nbsp'.html_safe %>
  </tr>
</thead>

app/views/businesses/_table_row.html.erb
 <tr>
     <td><%= link_to table_row.name, table_row %></td>
     <td><%= table_row.city %></td>
     <td><%= table_row.avg_speed==0 ? "N/A" : table_row.avg_speed %></td>
     <td><%= table_row.avg_quality==0 ? "N/A" : table_row.avg_quality %></td>
     <td><%= table_row.avg_usability==0 ? "N/A" : table_row.avg_usability %></td>
     <td><%= table_row.avg_affordability==0 ? "N/A" : table_row.avg_affordability %></td>
     <td><%= table_row.avg_warranty==0 ? "N/A" : table_row.avg_warranty %></td>
     <td><%= table_row.avg_kindness==0 ? "N/A" : table_row.avg_kindness %></td>
     <td><%= table_row.avg_review==0 ? "N/A" : table_row.avg_review %></td>
     <%= !params[:search_near].blank? ? ("<td>"+ table_row.distance.round(1).to_s + "</td>").html_safe : '&nbsp'.html_safe %>
</tr>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<div class="container">
  <div class="row">
    <div class="span16">
      <h3> Listing all businesses! </h3>
    </div>
  </div>

  <%= render :partial => "searches/form"%>

  <hr/>

  <div class="row">
    <table id="listBusinesses" class="tablesorter">
      <thead> 
          <tr>
            <th>Name</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Phone</th>
            <th>Url</th>
          </tr>
      </thead>
      <tbody>
        <% @businesses.each do |business| %>
          <tr>
            <td><%= link_to business.name, business %></td>
            <td><%= business.address %></td>
            <td><%= business.city %></td>
            <td><%= business.state %></td>
            <td><%= business.phone %></td>
            <td><%= business.url %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%=  render :partial => '/shared/tablesorter_pager'%>
  </div>
</div>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<div class="container">
<br/>
<div id="businessName" class="row">
  <div class="span10">
    <h2><%= @business.name %> &nbsp &nbsp &nbsp <%=  render  :partial => 'reviews/review_summary_chart' unless @business.reviews.count==0 %></h2>
  </div>
  <div class="span6"><p>&nbsp</p></div>
</div>    

<div id="businessDetails" class="row">
  <div class="span11">
    <div class="row">
      <div class="span10">
          <div class="row">
            <div class="span10">
              <% @business.categories.order(:name).each do |category| %> 
                <%= link_to(category.name, root_path) %> &nbsp &nbsp &nbsp
              <% end %>
            </div>
          </div>
          <div class="row"><div class="span10"><p><%= @business.address %>, <%= @business.city %>, <%= @business.state %></p></div></div>
          <div class="row"><div class="span10"><p><%= @business.phone %></p></div></div>
          <div class="row"><div class="span10"><p><%= link_to_unless(@business.url.nil?, @business.url) %></p></div></div>
      </div>
      <div class="span1"><p>&nbsp</p></div>
    </div>
    <div class="row"><div class="span9"><p><%= @business.description %></p></div></div>
    <div class="row"><div class="span9">&nbsp</div></div>
  </div>
  <div id="businessMap" class="span5">
    <% if @business.address then %>
      <%= gmaps("markers" => {"data" => @json}, "map_options" => {"auto_zoom" => false, "zoom" => 11} ) %>
    <% end %>
  </div>
</div>

<hr/>
<div class="row">
  <div class="span16">
    <h4> Reviews for This Business: </h4>
  </div>
</div>

<% if @business.reviews.count==0 then %>
  <div>
    <p>There are no reviews for this business yet!</p>
  </div>
<% else %>
  <div id="businessReviews" class ="row">
    <div class="span16">
      <table id="listBusinesses" class="tablesorter">
        <thead> 
          <tr>
            <th> Reviewer </th>
            <th> Date </th>
            <th> Speed </th>
            <th> Quality </th>
            <th> Usability </th>
            <th> Affordability </th>
            <th> Warranty </th>
            <th> Kindness </th>
            <th> Comments </th>
          </tr>
        </thead>
        <tbody>
          <%= render  :partial => 'reviews/review', :collection => @business.reviews %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

<div class="row" style="background: #ffe4e1;">
  <div class="span5">
    <br/><br/>Have you done business with <%= @business.name %> and have something to say? SQUAWK'em using this form: 
  </div>
  <div class="span6"><br/><%= render  :partial => 'reviews/form' %></div>
  <div class="span5">&nbsp</div>
</div>


<div id="businessLinks" class="row">
  <div class="span16">
<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>
  </div>
</div>
</div>