config/routes.rb
Squawkem::Application.routes.draw do

  get "categories/index"

  get "categories/show"

  get "category/index"

  get "category/show"

  devise_for :users

  resources :businesses do
    resources :reviews
  end

  resources :categories
  
  resources :reviews

  resources :searches

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/thanks',  :to => 'pages#thanks'
  match '/tour',  :to => 'pages#tour'

  #match 'search/' => 'search#index'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

end

app/views/shared/_sign_in_form.html.erb
<div class="pull-right">
  <% if user_signed_in? %>
    <p>
      <font class="font_xs" color="black"> <strong> <%= current_user.email %> </strong></font>
      &nbsp
      <%= link_to(image_tag("config.png"),edit_user_registration_path('user'), :rel => "twipsy", :"data-original-title" => "My Account" )%>
      &nbsp
      <%= link_to(image_tag("sign-out.png"),destroy_user_session_path, :method => :delete, :rel => "twipsy", :"data-original-title" => "Sign Out" )%>
    </p>
  <% else %>
    <%= form_for("user", :url => user_session_path) do |f| %>
      <%= link_to(image_tag("sign-up.png"),new_user_registration_path, :rel => "twipsy", :"data-original-title" => "Sign Up" )%>
      &nbsp&nbsp <strong>ID:</strong> &nbsp<%= f.text_field :email, :class => "span3" %>
      &nbsp <strong>PW:</strong> &nbsp<%= f.password_field :password, :class => "span2" %>
      <%= submit_tag 'Sign in', :src => '/assets/sign-in.png', :type => 'image', :rel => "twipsy", :"data-original-title" => "Sign In" %>
      &nbsp&nbsp
      <%= link_to(image_tag("login.png"),new_password_path('user'), :rel => "twipsy", :"data-original-title" => "Forgot Password" )%>
    <% end %>
  <% end %>


</div>

app/views/shared/_tablesorter_pager.html.erb
<div id="pager" class="pager">
  <br/>
  <form>
    <img src="/assets/first.png" class="first"/>
    <img src="/assets/prev.png" class="prev"/>
    <input type="text" class="pagedisplay"/>
    <img src="/assets/next.png" class="next"/>
    <img src="/assets/last.png" class="last"/>
    <select class="pagesize">
      <option selected="selected"  value="10">10</option>
      <option value="20">20</option>
      <option value="30">30</option>
      <option  value="40">40</option>
    </select>
  </form>
</div>
<br/>
<br/>
<br/>