config/routes.rb
Squawkem::Application.routes.draw do

  get "categories/index"

  get "categories/show"

  get "category/index"

  get "category/show"

  devise_for :users

  resources :businesses do
    resources :reviews
  end

  resources :categories
  
  resources :reviews

  resources :searches

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/thanks',  :to => 'pages#thanks'
  match '/tour',  :to => 'pages#tour'

  #match 'search/' => 'search#index'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   
  def index
    
    @subtitle = "Home"

    @top_categories = Category.all.sort! { |a,b| b.businesses.size <=> a.businesses.size }.take(6)

    @categories = Category.order(:name)

    @new_businesses = Business.order(:created_at).take(10)
  
  end

end

app/views/home/_home_content.html.erb
<div class="container">

  <%= render :partial => "searches/form"%>

  <hr/>
  <div class="row">
    <div class="span16">
      <h4> Highest Rated Busineses: </h4>
    </div>
  </div>
  <div class="row">
    <div class="span16">
      <div class = "row" >   
          <% @top_categories.each do |c| %>
            <%= '</div><div class = "row">'.html_safe if @top_categories.index(c) == 3 %>
            <div class="span4">
              <b><%= link_to c.name, new_search_path( :search_for => '', :category_id => c.id  ) %></b>
              <ol>
                <% c.businesses.all.sort! {|a,b| b.avg_review <=> a.avg_review }.take(5).each do |b| %>
                  <li><%= link_to b.name, b %> <%= " (" + b.avg_review.to_s + ")" %></li>
                <% end %>
              </ol>
            </div>
            <%= '<div class="span1">&nbsp</div>'.html_safe unless @top_categories.index(c) == ( 2 || 4 )%>
          <% end %>
      </div>
    </div>
  </div>

  <hr/>
  <div class="row">
    <div class="span16">
      <h4> Browse Categories: </h4>
    </div>
  </div>
  <div class="row">
    <div class="span16">
      <div class = "row" >   
          <% @categories.each do |c| %>
            <%= '</div><div class = "row">'.html_safe if (@categories.index(c)+1)%3 == 1   %>
            <div class="span4">
              <b><%= link_to c.name, new_search_path( :search_for => '', :category_id => c.id  ) %> <%= c.businesses.size.to_s%></b>
            </div>
            <%= '<div class="span1">&nbsp</div>'.html_safe unless (@categories.index(c)+1)%3 == 0 %>
          <% end %>
      </div>
    </div>
  </div>

  <hr/>
  <div class="row">
    <div class="span16">
      <h4> Newest Businesses: </h4>
    </div>
  </div>
  <div class="row">
    <div class="span16">
      <% if @new_businesses.empty? then %>
        <div class="row"><div class="span16">Please help us fill our database by <%= link_to 'adding a new business', new_business_path %></div>
      <% else %>
        <div class="row">
          <div class="span16">
           <table id="listBusinesses" class="tablesorter">
              <%= render 'businesses/table_header' %>
              <tbody>
                <%= render :partial => "businesses/table_row", :collection => @new_businesses %>
              </tbody>
          </table>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span16">
      <p><%= link_to 'New business', new_business_path %></p>
    </div>
  </div>
</div>
 

app/views/home/_home_welcome.html.erb
<header class="jumbotron masthead" id="overview">
  <div class="inner">
    <div class="container">
      <h1>Find the best contractors for your home and garden project! </h1>
      <p class="lead">
        Our specialized rating system ensures that you choose the contractors that fit your needs best. 
      </p>
    </div>
  </div>
</header>

<br/><br/><br/><br/>

<div class="container">
  <div class="row">
    <div class="span5">
      <%= image_tag("welcome.png") %>
    </div>
    <div class="span1">
      &nbsp
    </div>
    <div class="span8" style="background:#FFFFFF;">
      <div class="row">
        <div class="span8">
          <br/>
          <p class="lead">
            Make an informed decision when choosing your next contractor by using reviews and ratings created by home owners like you. All businesses are rated along the following six dimensions on our site:
          </p>
          <div class="row">
            <div class="span3">
              <ul>
                <li><strong>Speed:</strong></li>
                <li><strong>Quality:</strong>  </li>
                <li><strong>Usability:</strong> </li>
              </ul>
            </div>
            <div class="span3">
              <ul>
                <li><strong>Affordability:</strong> </li>
                <li><strong>Warranty:</strong> </li>
                <li><strong>Kindliness:</strong> </li>
              </ul>
            </div>
          </div>
          <br/>
        </div>
      </div>
      <div class="row">
        <div class="span4">
          <%= button_to "Get Started", new_user_registration_path,:class => "btn medium primary", :method => :get, :rel => "twipsy", :"data-original-title" => "Sign Up" %>
        </div>
        <div class="span4">
          <%= button_to "Learn More", tour_path,:class => "btn medium primary", :method => :get, :rel => "twipsy", :"data-original-title" => "Take a tour" %>
        </div>
      </div>
    </div>
  </div>
</div>

<br/><br/><br/><br/>

 

app/views/home/index.html.erb
<% if user_signed_in? %>
  <%= render :partial => "home_content"%>
<% else %>
  <%= render :partial => "home_welcome"%>
<% end %>