config/routes.rb
Squawkem::Application.routes.draw do

  get "categories/index"

  get "categories/show"

  get "category/index"

  get "category/show"

  devise_for :users

  resources :businesses do
    resources :reviews
  end

  resources :categories
  
  resources :reviews

  resources :searches

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/thanks',  :to => 'pages#thanks'
  match '/tour',  :to => 'pages#tour'

  #match 'search/' => 'search#index'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

end

app/views/layouts/_footer.html.erb
<footer class="footer">    
  <div class="container">
    <div class="row">
      <div class="span16">
        <div class="row">
          <div class="span14">
            <ul class="nav">
              <li><%= link_to "Help", help_path %></li>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
              <li><%= link_to "Thanks", thanks_path %></li>
            </ul>
          </div>
          <div class="span2">
            <ul class="nav pull-right">
              <li><a href="#">Back to top</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
     <div class="centered span16">
      <span>Copyright 2012 Squawkem, Inc. All rights reserved.</span>
     </div>
    </div>
    <div class="row">
     <div class="span16">
      <span>&nbsp</span>
     </div>
    </div>
  </div>
</footer>

app/views/layouts/_ga.html.erb
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-28422351-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>

app/views/layouts/_header.html.erb
<div class="topbar" data-scrollspy="scrollspy" >
  <div class="topbar-inner">
    <div class="container">
      <a class="brand" href="/"><%=app%></a>
      <div class="brand"><%= image_tag("squawk_36_24.png") %></div>
      <ul class="nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Businesses", businesses_path %></li>
      </ul>       
          <%= render 'shared/sign_in_form' %>  
        
    </div>
  </div><!-- /topbar-inner -->
</div><!-- /topbar -->

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Squawk'em</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
	<%= render :partial => 'layouts/ga' if Rails.env.production? %>
	<%= csrf_meta_tags %>
</head>
<body>
	  <%= render 'layouts/header' %>
		<br/>

		<div class="container">
  		<p id="notice" class="alert-message warning"><%= notice %></p>
		</div>
	  	<%= yield %>
		<%= render 'layouts/footer' %>
		<%= yield :scripts %>
		<%= debug(params) if Rails.env.development? %>
</body>
</html>